---
title: "Data605_Assignment14"
author: "Mahmud Hasan Al Raji"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


The general form of the Taylor series expansion:

$f(x)$ $=$ $\int_{n=0}^{\infty}$ $f^n(a)/n!(x-a)^n$ 

So, the Taylor series of the function f(x) centered at 0:

$f(x)$ $=$ $\int_{n=0}^{\infty}$ $f^n(0)/n!(x^n)$ 

$=$ $f(0)$ + $f^1(0)/1!(x)$ + $f^2(0)/2!(x^2)$ +$f^3(0)/3!(x^3)$+......+$f^n(0)/n!(x^n)$-----------(1)

# Find the Taylor series expansion of the following funciotns:

# 1. $f(x) = 1/(1-x)$ 

$f(x) = 1/(1-x)$

$f(0) = 1$

Now, find the value of the 1st, 2nd, 3rd..... nth derivatives of the function at x=0 are:

$f^1(x)= 1/(1-x)^2$ 

$f^1(0)= 1$

$f^2(x)= 2/(1-x)^3$ 

$f^2(0)= 2$

$f^3(x)= 6/(1-x)^4$ 

$f^3(0)= 6$

$f^4(x)= 24/(1-x)^5$ 

$f^4(0)= 24$
....

So, putting all the values in equation-1 we get the Taylor expansion of the function, f(x)=1/(1-x):

$1/(1-x)= 1+ 1/1!(x^1) + 2/2!(x^2) + 6/3!(x^3) + 24/4!(x^4)+.....$
$=\int_{n=0}^{\infty}x^n$ 



# 2.$f(x)=e^x$

$f(x)=e^x$

$f(0)=e^0=1$

$f^1(x)=e^x$

$f^1(0)=e^0=1$

$f^2(x)=e^x$

$f^2(0)=e^0=1$

$f^3(x)=e^x$

$f^3(0)=e^0=1$

$f^4(x)=e^x$

$f^4(0)=e^0=1$
......

Hence, putting all the values in equaion-1 we the Taylor series for the function $f(x)=e^x$:

$e^x=1+1/1!(x)+x^2/2!+x^3/3!+x^4/4!+....=\int_{n=0}^{\infty}x^n/n!$ 


# 3. $f(x)=ln(1+x)$

$f(x)=ln(1+x)$
$f(0)=ln(1+0)=0$

$f^1(x)=1/(1+x)$
$f^1(0)=1/(1+0)=1$

$f^2(x)= -1/(1+x)^2$
$f^2(0)= -1/(1+0)^2=-1$

$f^3(x)= 2/(1+x)^3$
$f^3(0)= 2/(1+0)^3=2$

$f^4(x)= -6/(1+x)^4$
$f^4(0)= -6/(1+0)^4=-6$
....................

Hence, the Taylor series expansion of ln(1+x):

$ln(1+x)=0+1/1!x^1-1/2!x^2+2/3!x^3-6/4!x^4+....$

$=x-x^2/2+x^3/3-x^4/4+......$

$=$ $\int_{n=0}^{\infty}(-1)^{n+1} x^n/n$ 

# 4. $f(x)=x^{1/2}$

Now,

$f(x)=x^{1/2}$

$f(0)=0^{1/2}=0$

$f^1(x)=1/2x^{-1/2}$

$f^1(0)=1/2.0^{-1/2}=0$


$f^2(x)=-1/4x^{-3/2}$

$f^2(0)=-1/4.0^{-3/2}=0$


$f^3(x)=3/8x^{-5/2}$

$f^3(0)=3/8.0^{-5/2}=0$
..................

It is found above that the function $f(x)=x^{1/2}$ is not possible to be differentiated at 0. Therefore, this function cannot be approximated with the Taylor series expansion.









